### PR TITLE
fix empty string values added to query string

### LINKED ISSUE #237: Remove empty radius
When ra,dec are set but no radius it MUST only query for that and remove radius

The issue comes when a search is made for example
image
Then you manually remove the radius value, the next search will send this parameters
image
But when you click clear and try again the query just send the ra and dec fields
image

### PR DESCRIPTION
**Pull request by dirodriguezm**
Closes #237

### CODE REVIEW

File: plugins/axios.js [hunk 1]
```diff
@@ -20,6 +20,13 @@ function renameFields(params) {
...
+function filterFunc(prefix, value) {
+  if (value === '') {
+    return
+  }
+  return value
+}
+
 export default function ({ $axios, store, redirect }, inject) {
   const ztfApi = $axios.create({
     baseURL: 'http://dev.api.alerce.online/',
```
Comment (JavierArredondo) [inline plugins/axios.js:32]: We must change this static api. Extract url of api from dot env files

Comment (JavierArredondo) [reply plugins/axios.js:32]: @dirodriguezm is this another issue?

Comment (dirodriguezm) [reply plugins/axios.js:32]: Yes that should be in another issue. I will add it now
